[2025-03-03T06:00:29.799+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_query.create_dim_monthly_customers_retention manual__2025-03-03T05:39:13.029042+00:00 [queued]>
[2025-03-03T06:00:29.831+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_query.create_dim_monthly_customers_retention manual__2025-03-03T05:39:13.029042+00:00 [queued]>
[2025-03-03T06:00:29.831+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-03-03T06:00:30.088+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_dim_monthly_customers_retention> on 2025-03-03 05:39:13.029042+00:00
[2025-03-03T06:00:30.232+0000] {standard_task_runner.py:57} INFO - Started process 18584 to run task
[2025-03-03T06:00:30.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pipeline_query', 'create_dim_monthly_customers_retention', 'manual__2025-03-03T05:39:13.029042+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_query.py', '--cfg-path', '/tmp/tmpbvo2znwo']
[2025-03-03T06:00:30.244+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask create_dim_monthly_customers_retention
[2025-03-03T06:00:30.598+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T06:00:30.789+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pipeline_query.create_dim_monthly_customers_retention manual__2025-03-03T05:39:13.029042+00:00 [running]> on host 9b8c8285a7ac
[2025-03-03T06:00:31.187+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'create_dim_monthly_customers_retention', field 'sql'. Template: 'create_dim_monthly_customers_rentention.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_dim_monthly_customers_rentention.sql
[2025-03-03T06:00:31.191+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 153, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_dim_monthly_customers_rentention.sql
[2025-03-03T06:00:31.247+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_pipeline_query, task_id=create_dim_monthly_customers_retention, execution_date=20250303T053913, start_date=20250303T060029, end_date=20250303T060031
[2025-03-03T06:00:31.687+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 50 for task create_dim_monthly_customers_retention (create_dim_monthly_customers_rentention.sql; 18584)
[2025-03-03T06:00:31.738+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-03T06:00:31.832+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
