[2025-03-03T04:14:28.985+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline_query.create_fact_query manual__2025-03-03T03:34:28.452047+00:00 [queued]>
[2025-03-03T04:14:29.023+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline_query.create_fact_query manual__2025-03-03T03:34:28.452047+00:00 [queued]>
[2025-03-03T04:14:29.025+0000] {taskinstance.py:1308} INFO - Starting attempt 8 of 9
[2025-03-03T04:14:29.375+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_fact_query> on 2025-03-03 03:34:28.452047+00:00
[2025-03-03T04:14:29.415+0000] {standard_task_runner.py:57} INFO - Started process 6137 to run task
[2025-03-03T04:14:29.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_pipeline_query', 'create_fact_query', 'manual__2025-03-03T03:34:28.452047+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline_query.py', '--cfg-path', '/tmp/tmpb5jcw68i']
[2025-03-03T04:14:29.424+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask create_fact_query
[2025-03-03T04:14:30.438+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:14:30.813+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_pipeline_query.create_fact_query manual__2025-03-03T03:34:28.452047+00:00 [running]> on host 9b8c8285a7ac
[2025-03-03T04:14:31.520+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raffi' AIRFLOW_CTX_DAG_ID='dag_pipeline_query' AIRFLOW_CTX_TASK_ID='create_fact_query' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:34:28.452047+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T03:34:28.452047+00:00'
[2025-03-03T04:14:31.521+0000] {sql.py:262} INFO - Executing: CREATE TABLE IF NOT EXISTS fact_employee AS
select 
*
from tbl_employee te 
where te.active = 'true'
[2025-03-03T04:14:31.565+0000] {base.py:73} INFO - Using connection ID '***_default' for task execution.
[2025-03-03T04:14:31.703+0000] {base.py:73} INFO - Using connection ID '***_default' for task execution.
[2025-03-03T04:14:31.727+0000] {sql.py:375} INFO - Running statement: CREATE TABLE IF NOT EXISTS fact_employee AS
select 
*
from tbl_employee te 
where te.active = 'true', parameters: None
[2025-03-03T04:14:32.218+0000] {sql.py:384} INFO - Rows affected: 260
[2025-03-03T04:14:32.586+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_pipeline_query, task_id=create_fact_query, execution_date=20250303T033428, start_date=20250303T041428, end_date=20250303T041432
[2025-03-03T04:14:33.567+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-03-03T04:14:33.633+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
