[2025-03-03T03:14:44.211+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_full_load.full_load_tbl_payment_method manual__2025-03-03T03:13:10.466139+00:00 [queued]>
[2025-03-03T03:14:44.238+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_full_load.full_load_tbl_payment_method manual__2025-03-03T03:13:10.466139+00:00 [queued]>
[2025-03-03T03:14:44.241+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-03-03T03:14:45.015+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): full_load_tbl_payment_method> on 2025-03-03 03:13:10.466139+00:00
[2025-03-03T03:14:45.046+0000] {standard_task_runner.py:57} INFO - Started process 830 to run task
[2025-03-03T03:14:45.055+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_full_load', 'full_load_tbl_payment_method', 'manual__2025-03-03T03:13:10.466139+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_full_load.py', '--cfg-path', '/tmp/tmpiyflt020']
[2025-03-03T03:14:45.061+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask full_load_tbl_payment_method
[2025-03-03T03:14:45.690+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T03:14:45.909+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_full_load.full_load_tbl_payment_method manual__2025-03-03T03:13:10.466139+00:00 [running]> on host 9b8c8285a7ac
[2025-03-03T03:14:47.094+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raffi' AIRFLOW_CTX_DAG_ID='dag_full_load' AIRFLOW_CTX_TASK_ID='full_load_tbl_payment_method' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:13:10.466139+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T03:13:10.466139+00:00'
[2025-03-03T03:14:47.101+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_load_tbl_payment_method.py", line 8, in full_load_tbl_payment_method
    df_payment_method = pd.read_csv("df_payment_method")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'df_payment_method'
[2025-03-03T03:14:48.301+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_full_load, task_id=full_load_tbl_payment_method, execution_date=20250303T031310, start_date=20250303T031444, end_date=20250303T031448
[2025-03-03T03:14:48.988+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task full_load_tbl_payment_method ([Errno 2] No such file or directory: 'df_payment_method'; 830)
[2025-03-03T03:14:49.051+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-03-03T03:14:49.342+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
